//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppShared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppShared.Resources.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Админ.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string Comment_many {
            get {
                return ResourceManager.GetString("Comment.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакт.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакты.
        /// </summary>
        public static string ContactPerson_many {
            get {
                return ResourceManager.GetString("ContactPerson.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конкурс.
        /// </summary>
        public static string Contest {
            get {
                return ResourceManager.GetString("Contest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конкурсы.
        /// </summary>
        public static string Contest_many {
            get {
                return ResourceManager.GetString("Contest.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документ.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документы.
        /// </summary>
        public static string Document_many {
            get {
                return ResourceManager.GetString("Document.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эксперт.
        /// </summary>
        public static string Expert {
            get {
                return ResourceManager.GetString("Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Письмо.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Письма.
        /// </summary>
        public static string Feedback_many {
            get {
                return ResourceManager.GetString("Feedback.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Населенный пункт.
        /// </summary>
        public static string GeoLocation {
            get {
                return ResourceManager.GetString("GeoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Населенные пункты.
        /// </summary>
        public static string GeoLocation_many {
            get {
                return ResourceManager.GetString("GeoLocation.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип населенного пункта.
        /// </summary>
        public static string GeoLocationType {
            get {
                return ResourceManager.GetString("GeoLocationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типы населенных пунктов.
        /// </summary>
        public static string GeoLocationType_many {
            get {
                return ResourceManager.GetString("GeoLocationType.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поселения.
        /// </summary>
        public static string GeoMunicipality {
            get {
                return ResourceManager.GetString("GeoMunicipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поселения.
        /// </summary>
        public static string GeoMunicipality_many {
            get {
                return ResourceManager.GetString("GeoMunicipality.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип поселения.
        /// </summary>
        public static string GeoMunicType {
            get {
                return ResourceManager.GetString("GeoMunicType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типы поселений.
        /// </summary>
        public static string GeoMunicType_many {
            get {
                return ResourceManager.GetString("GeoMunicType.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Район.
        /// </summary>
        public static string GeoRegion {
            get {
                return ResourceManager.GetString("GeoRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Районы.
        /// </summary>
        public static string GeoRegion_many {
            get {
                return ResourceManager.GetString("GeoRegion.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Центр.
        /// </summary>
        public static string GeoRegionCenter {
            get {
                return ResourceManager.GetString("GeoRegionCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Центры районов.
        /// </summary>
        public static string GeoRegionCenter_many {
            get {
                return ResourceManager.GetString("GeoRegionCenter.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Урок.
        /// </summary>
        public static string Lesson {
            get {
                return ResourceManager.GetString("Lesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уроки.
        /// </summary>
        public static string Lesson_many {
            get {
                return ResourceManager.GetString("Lesson.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string LessonCategory {
            get {
                return ResourceManager.GetString("LessonCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категории.
        /// </summary>
        public static string LessonCategory_many {
            get {
                return ResourceManager.GetString("LessonCategory.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Модератор.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участник.
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плейлист.
        /// </summary>
        public static string Playlist {
            get {
                return ResourceManager.GetString("Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плейлисты.
        /// </summary>
        public static string Playlist_many {
            get {
                return ResourceManager.GetString("Playlist.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новость.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новости.
        /// </summary>
        public static string Post_many {
            get {
                return ResourceManager.GetString("Post.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Школа.
        /// </summary>
        public static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Школы.
        /// </summary>
        public static string School_many {
            get {
                return ResourceManager.GetString("School.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Класс.
        /// </summary>
        public static string SchoolClass {
            get {
                return ResourceManager.GetString("SchoolClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Классы.
        /// </summary>
        public static string SchoolClass_many {
            get {
                return ResourceManager.GetString("SchoolClass.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись класса.
        /// </summary>
        public static string SchoolClassPost {
            get {
                return ResourceManager.GetString("SchoolClassPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записи класса.
        /// </summary>
        public static string SchoolClassPost_many {
            get {
                return ResourceManager.GetString("SchoolClassPost.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись школы.
        /// </summary>
        public static string SchoolPost {
            get {
                return ResourceManager.GetString("SchoolPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Школьные записи.
        /// </summary>
        public static string SchoolPost_many {
            get {
                return ResourceManager.GetString("SchoolPost.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История статуса.
        /// </summary>
        public static string StatusChangeHistory {
            get {
                return ResourceManager.GetString("StatusChangeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Истории статусов.
        /// </summary>
        public static string StatusChangeHistory_many {
            get {
                return ResourceManager.GetString("StatusChangeHistory.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string User_many {
            get {
                return ResourceManager.GetString("User.many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} не является действительным адресом электронной почты..
        /// </summary>
        public static string v_email {
            get {
                return ResourceManager.GetString("v_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для поля {0} минимальная длина {1}, максимальная {2}.
        /// </summary>
        public static string v_range {
            get {
                return ResourceManager.GetString("v_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} обязательно для заполнения..
        /// </summary>
        public static string v_required {
            get {
                return ResourceManager.GetString("v_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Читатель.
        /// </summary>
        public static string Viewer {
            get {
                return ResourceManager.GetString("Viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявка.
        /// </summary>
        public static string Zayavka {
            get {
                return ResourceManager.GetString("Zayavka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявки.
        /// </summary>
        public static string Zayavka_many {
            get {
                return ResourceManager.GetString("Zayavka.many", resourceCulture);
            }
        }
    }
}
